version: 0.1

phases:
  build:
    commands:
      - echo "Starting build `date` in `pwd`"
      - npm install
      - npm run aws-build
  post_build:
    commands:
      - echo "build completed on `date`"
