---
AWSTemplateFormatVersion: '2010-09-09'
Description: Blog resources
Resources:
  S3Bucket:
    Type: "AWS::S3::Bucket"
    Properties:
      BucketName: blog.disasterdev.net
      # AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: error.html

  S3BucketPolicy:
    Type: "AWS::S3::BucketPolicy"
    Properties: 
      Bucket: !Ref S3Bucket
      PolicyDocument:
        Statement: 
          - Action: 
              - "s3:GetObject"
            Effect: "Allow"
            Resource: !Join
              - ""
              - - "arn:aws:s3:::"
                - !Ref S3Bucket
                - "/*"
            Principal:
              AWS: "*"

  CloudFront:
    Type: "AWS::CloudFront::Distribution"
    Properties:
      DistributionConfig:
        Aliases:
          - "blog.disasterdev.net"
        Comment: CloudFront for Blog
        Enabled: true
        DefaultCacheBehavior:
          Compress: true
          ForwardedValues:
            QueryString: true
          TargetOriginId: blog-origin
          ViewerProtocolPolicy: redirect-to-https
          DefaultTTL: 0
        Origins:
          - DomainName: !Join
              - ''
              - - !Ref S3Bucket
                -  ".s3-website-ap-southeast-2.amazonaws.com"
            CustomOriginConfig:
              HTTPPort: 80
              HTTPSPort: 443
              OriginProtocolPolicy: http-only
            Id: blog-origin
            # S3OriginConfig:
            #   OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${OriginAccessIdentity}"
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: "arn:aws:acm:us-east-1:504224764639:certificate/866de211-71e2-45ee-971c-db1180e6cddd"
          SslSupportMethod: sni-only
        DefaultRootObject: "index.html"

  # OriginAccessIdentity:
  #   Type: "AWS::CloudFront::CloudFrontOriginAccessIdentity"
  #   Properties:
  #     CloudFrontOriginAccessIdentityConfig:
  #       Comment: "Blog OAI"

  RecourdSet:
    Type : "AWS::Route53::RecordSet"
    Properties:
      Name: "blog.disasterdev.net"
      Comment: "A record for Blog"
      HostedZoneId: "Z3MTVYTKZKL49"
      AliasTarget:
        DNSName: !GetAtt CloudFront.DomainName
        HostedZoneId: Z2FDTNDATAQYW2
      Type: A
